### ISSUE TITLE
Document explicitly (in README?) that ASE and OMM give different physics (integrators etc)

### ISSUE THREAD

**Issue by Ragzouken** [IRL2/nanover-docs#109]
Reported for nanotube in SubtleGame

**Comment by hjstroud** [comment]
@Ragzouken @rhoslynroebuck as this issue been resolved? I seem to remember that the integrator parameters themselves were different (i.e. different friction coefficients for the Langevin integrators of OMM and ASE), and if I recall correctly the ASE integrator had a much lower friction coefficient, which would explain why the dynamics seem much more responsive with the ASE integrator. 

I agree with @jbarnoud that different implementations of the same integrator approach could still produce different dynamics, so it is unlikely that we would be able to get 1:1 agreement between OMM and ASE. However if we were to set the integration parameters to be equivalent in the integrators, we should at least get _similar_ dynamics: has this been tested?

If it is only an issue with the friction parameters, I would recommend closing this issue and opening an issue about not currently being able to change the OMM-ASE default integrator parameters on the nanover-protocol repo.

**Comment by rhoslynroebuck** [comment]
Yeah I think this has been resolved.
