### ISSUE TITLE
Add funding bodies to docs

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-docs#28]
We could add logos of the funding bodies to the docs (either in one place or on every page, depending on how numerous they are).

One question to address is how far back do we need to go in terms of acknowledging
funding bodies? (e.g. do we need to acknowledge any funding body that contributed to Narupa?)

**Comment by rhoslynroebuck** [comment]
Confirmation from Dave, we should add something that says "currently supported by" and includes all current funding bodies (ERC and Xunta de Galicia).
