### ISSUE TITLE
Automate the building of the documentation

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-docs#3]
The documentation needs to be rebuilt under two conditions:
* when the documentation source is updated
* when the nanover-protocol repository is updated

Tasks:
* [X] Have sphinx run from a workflow on push (PR #1)
* [X] Run the sphinx workflow when the nanover-protocol submodule is updated (PR #1 and #2)
* [x] Update the nanover-protocol submodule when nanover-protocol is updated
    * [x] Accept API triggering the submodule update workflow
    * [x] Trigger the workflow from nanover-protocol

**Comment by hjstroud** [comment]
@Ragzouken What do you reckon we should do about this?

**Comment by Ragzouken** [comment]
Someone, perhaps me, needs to learn how to set up the github actions for both docs repo and nanover-protocol to do this--not sure where it falls in priority, bring it up in a meeting I guess.

**Comment by hjstroud** [comment]
This has been completed, see IRL2/nanover-protocol#286. Thanks @rhoslynroebuck for helping do this!
