### ISSUE TITLE
Rename repo to `nanover-docs`

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-docs#33]
It's confusing that the `nanover` repo only contains documentation: perhaps it would be clearer if it were renamed as per the title of this issue.

**Comment by rhoslynroebuck** [comment]
I'm not sure this is easy to do...from googling I'm worried it will break the link to the auto-generated documentation. 

@jbarnoud do you know we can do this?

**Comment by jbarnoud** [comment]
It would change the URL to nanover-docs.gitHub.io that's the reason I hijacked the nanover repo.

**Comment by rhoslynroebuck** [comment]
What's the problem with this changing the URL? That it might be confusing for people who are already using the current URL?

**Comment by jbarnoud** [comment]
It is not a problem. I am just stating the consequence 😃

**Comment by rhoslynroebuck** [comment]
Aha OK, thanks!
