### ISSUE TITLE
Favicon doesn't work on Safari

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover-docs#38]

**Comment by rhoslynroebuck** [comment]
This now works on Safari if you go to any specific page on the documentation, but not if you go to `https://irl2.github.io/nanover/`

**Comment by hjstroud** [comment]
The new link to the documentation is `https://irl2.github.io/nanover-docs/`

This issue appears to have been resolved for the time being, so shall be closed.
