### ISSUE TITLE
Documentation tab labelled 2018.1.8

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-docs#41]
See screenshot below:

![Screenshot 2024-07-17 at 16 16 11](https://github.com/user-attachments/assets/87c496f8-30fb-42fe-94d7-5464a191b982)

This may relate to how we want to version NanoVer, but at the least it should probably say this year...

**Comment by Mohamed-Dhouioui** [comment]
This can be modified in **source/conf.py**  :
`# The full version, including alpha/beta/rc tags`
`release = '2018.1.8'
`
I wonder if it can be automatically updated by being linked to releases ?

**Comment by hjstroud** [comment]
> This can be modified in **source/conf.py** : `# The full version, including alpha/beta/rc tags` `release = '2018.1.8' ` I wonder if it can be automatically updated by being linked to releases ?

That's an excellent idea!
