### ISSUE TITLE
GitHub Pages site isn't live

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover-docs#90]
Since last Friday (~midday), the [github pages](https://irl2.github.io/nanover-docs/index.html) site has been down with the following message:

![image](https://github.com/user-attachments/assets/f2e4202a-8b2a-4d59-a7f4-2759fa116e68)

We have made no changes to `main` and before this issue started, `main` was passing all of the tests. Now `main` (and all other branches we have tested) are failing the tests with the following error:

![image](https://github.com/user-attachments/assets/2efff560-50d5-4a3d-97b6-4eef0a00dfed)

With the main error being: `Error: fatal: couldn't find remote ref refs/heads/pages`

EDIT:
Note that the repo builds fine locally.

**Comment by rhoslynroebuck** [comment]
@Ragzouken Do you have any idea about this? I had a google but still not sure what the problem is....

**Comment by Ragzouken** [comment]
It seems you mistakenly deleted this branch `pages` which is used as part of the docs build process:

![image](https://github.com/user-attachments/assets/29ccb402-37b4-4971-bd56-fa7786b70a14)

Maybe we consider some better naming scheme for it so it's clear it's not a temporary branch? I've restored the branch though, so things should work again.

**Comment by Ragzouken** [comment]
That fixes the build but the site is still not available. Not sure about that..

**Comment by Ragzouken** [comment]
Something to do with this https://github.com/IRL2/nanover-docs/actions/runs/10558206040/job/29247319593
![image](https://github.com/user-attachments/assets/ba3096f2-3e80-42ae-9d32-a9f3375ee8af)

**Comment by Ragzouken** [comment]
I've made the `pages` branch "protected" so it can't easily be deleted

**Comment by Ragzouken** [comment]
Should now be working again!

**Comment by rhoslynroebuck** [comment]
Ah amazing, thanks so much @Ragzouken ! I must've accidentally deleted from my GitHub desktop app, thanks for sorting this.
